use arca_air::{AirFunction, AirInstruction, AirModule, AirTerminator, AirValue, BasicBlock, BlockId, RegisterId};
use arca_ast::BinaryOp;
use arca_typechecker::{PrimitiveType, Type};
use std::collections::{HashMap, HashSet};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BackendKind { Native, Llvm, C }

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TargetArch { X86_64, Arm64, Riscv64, Wasm, C }

pub struct CodeGenerator {
    backend: BackendKind,
    target: TargetArch,
    var_names: HashMap<RegisterId, String>,
    used_names: HashSet<String>,
    name_counter: HashMap<String, u32>,
    param_targets: HashSet<RegisterId>,
    param_c_names: HashMap<RegisterId, String>,
    output: String,
    indent: usize,
    return_type_is_void: bool,
}

impl CodeGenerator {
    pub fn new(backend: BackendKind, target: TargetArch) -> Self {
        Self {
            backend, target,
            var_names: HashMap::new(), used_names: HashSet::new(),
            name_counter: HashMap::new(),
            param_targets: HashSet::new(), param_c_names: HashMap::new(),
            output: String::new(), indent: 0, return_type_is_void: false,
        }
    }

    fn reg_name(&mut self, reg: RegisterId, hint: &str) -> String {
        let safe = hint.replace('.', "_");
        if let Some(name) = self.var_names.get(&reg) {
            return name.clone();
        }
        let base = if safe.is_empty() || safe.chars().all(|c| c.is_numeric()) {
            "t".to_string()
        } else {
            safe
        };
        let count = self.name_counter.entry(base.clone()).or_insert(0);
        let name = if *count > 0 || self.used_names.contains(&base) {
            format!("{}_{}", base, *count)
        } else {
            base
        };
        *count += 1;
        self.used_names.insert(name.clone());
        self.var_names.insert(reg, name.clone());
        name
    }

    fn emit(&mut self, s: &str) { self.output.push_str(s); }
    fn emit_ln(&mut self, s: &str) {
        self.output.push_str(&"  ".repeat(self.indent));
        self.output.push_str(s); self.output.push('\n');
    }
    fn emit_indent(&mut self) { self.output.push_str(&"  ".repeat(self.indent)); }

    fn air_type_to_c(&self, ty: &Type) -> &str {
        match ty {
            Type::Primitive(p) => match p {
                PrimitiveType::I8 => "int8_t", PrimitiveType::I16 => "int16_t",
                PrimitiveType::I32 => "int32_t", PrimitiveType::I64 => "int64_t",
                PrimitiveType::U8 => "uint8_t", PrimitiveType::U16 => "uint16_t",
                PrimitiveType::U32 => "uint32_t", PrimitiveType::U64 => "uint64_t",
                PrimitiveType::F32 => "float", PrimitiveType::F64 => "double",
                PrimitiveType::Bool => "bool", PrimitiveType::String => "const char*",
                PrimitiveType::Char => "char", PrimitiveType::Void => "void",
            },
            _ => "int64_t",
        }
    }

    fn emit_air_value(&mut self, val: &AirValue) {
        match val {
            AirValue::ConstInt(n) => self.emit(&n.to_string()),
            AirValue::ConstFloat(f) => self.emit(&f.to_string()),
            AirValue::ConstBool(b) => self.emit(if *b { "1" } else { "0" }),
            AirValue::ConstString(s) => {
                let e = s.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n");
                self.emit(&format!("\"{}\"", e));
            }
            AirValue::Register(r) => {
                self.emit(&self.var_names.get(r).cloned().unwrap_or(format!("r{}", r.0)));
            }
        }
    }

    pub fn generate_c_from_air(&mut self, module: &AirModule) -> String {
        self.output.clear();
        self.emit("// Generated by Arca C Backend (AIR)\n");
        self.emit("#include \"arca_runtime.h\"\n\n");

        for (name, func) in &module.functions {
            let safe = if name == "main" { "arca_main" } else { name };
            let ret = self.air_type_to_c(&func.return_type);
            let mut d = format!("{} {}(", ret, safe);
            if func.params.is_empty() { d.push_str("void"); }
            else {
                for (i, (_, pt)) in func.params.iter().enumerate() {
                    if i > 0 { d.push_str(", "); }
                    d.push_str(self.air_type_to_c(pt));
                }
            }
            d.push_str(");\n");
            self.emit(&d);
        }
        self.emit("\n");

        for (name, func) in &module.functions {
            self.emit_function(name, func);
            self.emit("\n");
        }

        if module.functions.contains_key("main") {
            self.emit("int main(int argc, char** argv) {\n  arca_main();\n  return 0;\n}\n");
        }

        self.output.clone()
    }

    fn emit_function(&mut self, name: &str, func: &AirFunction) {
        self.var_names.clear(); self.used_names.clear();
        self.name_counter.clear(); self.param_targets.clear();
        self.param_c_names.clear();
        self.return_type_is_void = matches!(&func.return_type, Type::Primitive(PrimitiveType::Void));

        let safe_name = if name == "main" { "arca_main" } else { name };
        let ret_c = self.air_type_to_c(&func.return_type).to_string();
        let block_map: HashMap<BlockId, &BasicBlock> = func.blocks.iter().map(|b| (b.id, b)).collect();

        // Build param register -> C name mapping
        let mut param_reg_names: HashMap<RegisterId, String> = HashMap::new();
        for (i, (pname, _pty)) in func.params.iter().enumerate() {
            let cname = pname.replace('.', "_");
            if i < func.param_registers.len() {
                param_reg_names.insert(func.param_registers[i], cname);
            }
        }

        // Emit signature
        let mut sig = format!("{} {}(", ret_c, safe_name);
        if func.params.is_empty() {
            sig.push_str("void");
        } else {
            for (i, (pname, pty)) in func.params.iter().enumerate() {
                if i > 0 { sig.push_str(", "); }
                sig.push_str(self.air_type_to_c(pty));
                sig.push(' ');
                sig.push_str(&pname.replace('.', "_"));
            }
        }
        sig.push_str(") {\n");
        self.emit(&sig);
        self.indent += 1;

        // First pass: declare all registers.
        // Pre-register param names so they're available when used as operands.
        for (reg, cname) in &param_reg_names {
            self.var_names.insert(*reg, cname.clone());
        }

        for block in &func.blocks {
            for instr in &block.instructions {
                let (reg, ctype_str) = match instr {
                    AirInstruction::Alloca { target, ty } => {
                        (Some(*target), Some(self.air_type_to_c(ty).to_string()))
                    }
                    AirInstruction::Load { target, .. } => (Some(*target), Some("int64_t".to_string())),
                    AirInstruction::Binary { target, .. } => (Some(*target), Some("int64_t".to_string())),
                    AirInstruction::Call { target, .. } => {
                        if let Some(t) = target { (Some(*t), Some("int64_t".to_string())) } else { (None, None) }
                    }
                    AirInstruction::StructInit { target, .. } => (Some(*target), Some("int64_t".to_string())),
                    AirInstruction::FieldLoad { target, .. } => (Some(*target), Some("int64_t".to_string())),
                    AirInstruction::Ref { target, .. } => (Some(*target), Some("void*".to_string())),
                    AirInstruction::Deref { target, .. } => (Some(*target), Some("int64_t".to_string())),
                    _ => (None, None),
                };
                if let (Some(r), Some(ct)) = (reg, ctype_str) {
                    if !param_reg_names.contains_key(&r) {
                        let n = self.reg_name(r, "");
                        // Use int64_t for all allocas to prevent 32-bit truncation
                        let t = if matches!(instr, AirInstruction::Alloca { .. }) { "int64_t" } else { &ct };
                        self.emit_ln(&format!("{} {};", t, n));
                    }
                }
            }
        }

        // Emit blocks
        let entry = func.entry_block;
        for block in &func.blocks {
            if block.id != entry {
                self.emit_ln(&format!("bb_{}: ;", block.id.0));
            }
            for instr in &block.instructions {
                self.emit_air_instr(instr);
            }
            self.emit_air_terminator(&block.terminator);
        }

        self.indent -= 1;
        self.emit("}\n");
    }

    fn emit_air_instr(&mut self, instr: &AirInstruction) {
        match instr {
            AirInstruction::Alloca { .. } => {}
            AirInstruction::Store { ptr, val } => {
                let pn = self.var_names.get(ptr).cloned().unwrap_or_default();
                self.emit_indent(); self.emit(&pn); self.emit(" = "); self.emit_air_value(val); self.emit(";\n");
            }
            AirInstruction::Load { target, ptr, .. } => {
                let tn = self.var_names.get(target).cloned().unwrap_or_default();
                // If loading from a param register, the C param variable IS the value
                let sn = if self.param_c_names.contains_key(ptr) {
                    self.param_c_names[ptr].clone()
                } else {
                    self.var_names.get(ptr).cloned().unwrap_or_default()
                };
                self.emit_ln(&format!("{} = {};", tn, sn));
            }
            AirInstruction::Binary { target, op, left, right } => {
                let tn = self.var_names.get(target).cloned().unwrap_or_default();
                let os = match op {
                    BinaryOp::Add => " + ", BinaryOp::Sub => " - ", BinaryOp::Mul => " * ",
                    BinaryOp::Div => " / ", BinaryOp::Rem => " % ",
                    BinaryOp::Equal => " == ", BinaryOp::NotEqual => " != ",
                    BinaryOp::Less => " < ", BinaryOp::LessEqual => " <= ",
                    BinaryOp::Greater => " > ", BinaryOp::GreaterEqual => " >= ",
                    BinaryOp::And => " && ", BinaryOp::Or => " || ",
                };
                self.emit_indent(); self.emit(&tn); self.emit(" = "); self.emit_air_value(left);
                self.emit(os); self.emit_air_value(right); self.emit(";\n");
            }
            AirInstruction::Call { target, fn_name, args } => self.emit_air_call(target, fn_name, args),
            AirInstruction::StructInit { target, struct_name, fields } => {
                let tn = self.var_names.get(target).cloned().unwrap_or_default();
                self.emit_indent(); self.emit(&format!("{} = ({}){{", tn, struct_name));
                for (i, (fn_, fv)) in fields.iter().enumerate() {
                    if i > 0 { self.emit(", "); }
                    self.emit(&format!(".{}=", fn_)); self.emit_air_value(fv);
                }
                self.emit("};\n");
            }
            AirInstruction::FieldLoad { target, object, field } => {
                let tn = self.var_names.get(target).cloned().unwrap_or_default();
                let on = self.var_names.get(object).cloned().unwrap_or_default();
                self.emit_ln(&format!("{} = {}.{};", tn, on, field));
            }
            AirInstruction::Ref { target, source } => {
                let tn = self.var_names.get(target).cloned().unwrap_or_default();
                let sn = self.var_names.get(source).cloned().unwrap_or_default();
                self.emit_ln(&format!("{} = &{};", tn, sn));
            }
            AirInstruction::Deref { target, ptr } => {
                let tn = self.var_names.get(target).cloned().unwrap_or_default();
                let pn = self.var_names.get(ptr).cloned().unwrap_or_default();
                self.emit_ln(&format!("{} = *{};", tn, pn));
            }
        }
    }

    fn emit_air_call(&mut self, target: &Option<RegisterId>, fn_name: &str, args: &[AirValue]) {
        match fn_name {
            "println" => {
                for arg in args {
                    self.emit_indent(); self.emit("arca_print_");
                    match arg { AirValue::ConstString(_) => self.emit("string("), _ => self.emit("int("), }
                    self.emit_air_value(arg); self.emit(");\n");
                }
                self.emit_ln("putchar('\\n');");
                if let Some(t) = target { let n = self.var_names.get(t).cloned().unwrap_or_default(); self.emit_ln(&format!("{} = 0;", n)); }
            }
            "print" => {
                for arg in args {
                    self.emit_indent(); self.emit("arca_print_");
                    match arg { AirValue::ConstString(_) => self.emit("string("), _ => self.emit("int("), }
                    self.emit_air_value(arg); self.emit(");\n");
                }
                if let Some(t) = target { let n = self.var_names.get(t).cloned().unwrap_or_default(); self.emit_ln(&format!("{} = 0;", n)); }
            }
            "Instant.now" | "Instant_now" | "now" => {
                if let Some(t) = target { let n = self.var_names.get(t).cloned().unwrap_or_default(); self.emit_ln(&format!("{} = arca_time_ns();", n)); }
            }
            n if n.ends_with("elapsed_ms") => {
                if let Some(t) = target {
                    let tn = self.var_names.get(t).cloned().unwrap_or_default();
                    let tv = if !args.is_empty() { let mut s = String::new(); self.emit_air_value_in(&mut s, &args[0]); s } else { "0".to_string() };
                    self.emit_ln(&format!("{} = (arca_time_ns() - {}) / 1000000LL;", tn, tv));
                }
            }
            n if n.ends_with("elapsed_ns") => {
                if let Some(t) = target {
                    let tn = self.var_names.get(t).cloned().unwrap_or_default();
                    let tv = if !args.is_empty() { let mut s = String::new(); self.emit_air_value_in(&mut s, &args[0]); s } else { "0".to_string() };
                    self.emit_ln(&format!("{} = arca_time_ns() - {};", tn, tv));
                }
            }
            _ => {
                let pre = if let Some(t) = target { format!("{} = ", self.var_names.get(t).cloned().unwrap_or_default()) } else { String::new() };
                self.emit_indent(); self.emit(&pre); self.emit(fn_name); self.emit("(");
                for (i, arg) in args.iter().enumerate() { if i > 0 { self.emit(", "); } self.emit_air_value(arg); }
                self.emit(");\n");
            }
        }
    }

    fn emit_air_value_in(&self, out: &mut String, val: &AirValue) {
        match val {
            AirValue::ConstInt(n) => out.push_str(&n.to_string()),
            AirValue::ConstFloat(f) => out.push_str(&f.to_string()),
            AirValue::ConstBool(b) => out.push_str(if *b { "1" } else { "0" }),
            AirValue::ConstString(s) => { let e = s.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n"); out.push_str(&format!("\"{}\"", e)); }
            AirValue::Register(r) => { out.push_str(&self.var_names.get(r).cloned().unwrap_or(format!("r{}", r.0))); }
        }
    }

    fn emit_air_terminator(&mut self, term: &AirTerminator) {
        match term {
            AirTerminator::Br(t) => self.emit_ln(&format!("goto bb_{};", t.0)),
            AirTerminator::CondBr { cond, then_block, else_block } => {
                self.emit_indent(); self.emit("if ("); self.emit_air_value(cond);
                self.emit(&format!(") goto bb_{}; else goto bb_{};\n", then_block.0, else_block.0));
            }
            AirTerminator::Ret(opt) => {
                match opt {
                    Some(val) if !self.return_type_is_void => {
                        self.emit_indent(); self.emit("return "); self.emit_air_value(val); self.emit(";\n");
                    }
                    _ => self.emit_ln("return;"),
                }
            }
            AirTerminator::Unreachable => self.emit_ln("__builtin_unreachable();"),
        }
    }
}
