use arca_ast::{BinaryOp, LiteralKind, TypeAnnotation};
use arca_air::{AirModule};
use arca_hir::*;
use arca_typechecker::{PrimitiveType, Type};
use std::collections::HashMap;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BackendKind {
    Native,
    Llvm,
    C,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TargetArch {
    X86_64,
    Arm64,
    Riscv64,
    Wasm,
    C,
}

pub struct CodeGenerator {
    backend: BackendKind,
    target: TargetArch,
    var_ids: HashMap<String, u32>,
    next_var: u32,
    output: String,
    indent: usize,
}

impl CodeGenerator {
    pub fn new(backend: BackendKind, target: TargetArch) -> Self {
        Self { backend, target, var_ids: HashMap::new(), next_var: 0, output: String::new(), indent: 0 }
    }

    fn fresh_var(&mut self, name: &str) -> String {
        let id = self.next_var;
        self.next_var += 1;
        let safe = format!("{}_{}", name.replace('.', "_"), id);
        self.var_ids.insert(name.to_string(), id);
        safe
    }

    fn emit(&mut self, s: &str) { self.output.push_str(s); }
    fn emit_ln(&mut self, s: &str) { self.output.push_str(&"  ".repeat(self.indent)); self.output.push_str(s); self.output.push('\n'); }
    fn emit_indent(&mut self) { self.output.push_str(&"  ".repeat(self.indent)); }

    pub fn generate_c_from_hir(&mut self, hir: &HirProgram) -> String {
        self.output.clear();
        self.emit("// Generated by Arca C Backend\n");
        self.emit("#include <stdio.h>\n");
        self.emit("#include <stdint.h>\n");
        self.emit("#include <stdbool.h>\n");
        self.emit("#include <string.h>\n");
        self.emit("#include <stdlib.h>\n");
        // POSIX headers for extern functions
        self.emit("#include <unistd.h>\n");
        self.emit("#include <time.h>\n");
        self.emit("#include <sys/socket.h>\n");
        self.emit("#include <netinet/in.h>\n\n");

        // Runtime helpers
        self.emit("void arca_print_int(int64_t v) { printf(\"%lld\", (long long)v); }\n");
        self.emit("void arca_print_string(const char* s) { if(s) fwrite(s, strlen(s), 1, stdout); }\n");
        self.emit("void arca_println_int(int64_t v) { printf(\"%lld\\n\", (long long)v); }\n");
        self.emit("void arca_println_string(const char* s) { if(s) puts(s); else putchar('\\n'); }\n");
        self.emit("int64_t arca_time_ns(void) { struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts); return (int64_t)ts.tv_sec * 1000000000LL + (int64_t)ts.tv_nsec; }\n");
        self.emit("int64_t arca_time_ms(void) { struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts); return (int64_t)ts.tv_sec * 1000LL + ((int64_t)ts.tv_nsec / 1000000LL); }\n\n");

        // Struct types
        for (name, hir_struct) in &hir.structs {
            self.emit_ln(&format!("typedef struct {{"));
            self.indent += 1;
            for f in &hir_struct.fields {
                let ctype = self.hir_type_to_c(&f.type_ann, &hir.structs);
                self.emit_ln(&format!("{} {};", ctype, f.name));
            }
            self.indent -= 1;
            self.emit_ln(&format!("}} {};", name));
            self.emit_ln("");
        }

        // Forward declarations for user functions
        for (name, hir_fn) in &hir.functions {
            let safe_name = if name == "main" { "arca_main" } else { name.as_str() };
            self.emit_indent();
            let ret_type = hir_fn.return_type.as_ref()
                .map(|t| self.hir_type_to_c(t, &hir.structs))
                .unwrap_or_else(|| "int64_t".to_string());
            self.emit(&ret_type);
            self.emit(" ");
            self.emit(safe_name);
            self.emit("(");
            for (i, param) in hir_fn.params.iter().enumerate() {
                if i > 0 { self.emit(", "); }
                self.emit(&self.hir_type_to_c(&param.type_ann, &hir.structs));
            }
            self.emit(");\n");
        }
        self.emit_ln("");

        // Extern forward declarations
        for ext in &hir.externs {
            self.emit_indent();
            let ret_type = ext.return_type.as_ref()
                .map(|t| self.hir_type_to_c(t, &hir.structs))
                .unwrap_or_else(|| "void".to_string());
            self.emit(&ret_type);
            self.emit(" ");
            self.emit(&ext.name);
            self.emit("(");
            for (i, param) in ext.params.iter().enumerate() {
                if i > 0 { self.emit(", "); }
                self.emit(&self.hir_type_to_c(&param.type_ann, &hir.structs));
            }
            self.emit(");\n");
        }
        self.emit_ln("");

        // Extern implementations (raw C code)
        for ext in &hir.externs {
            if !ext.body.is_empty() {
                self.emit_ln(&ext.body);
                self.emit_ln("");
            }
        }

        // Function implementations
        for (name, hir_fn) in &hir.functions {
            self.emit_fn(name, hir_fn, &hir.structs, &hir.functions, &hir.externs);
            self.emit_ln("");
        }

        // Main wrapper — C main calls arca_main
        self.emit_ln("int main(int argc, char** argv) {");
        self.indent += 1;
        if hir.functions.contains_key("main") {
            self.emit_ln("arca_main();");
        }
        self.emit_ln("return 0;");
        self.indent -= 1;
        self.emit_ln("}");

        self.output.clone()
    }

    fn emit_fn(&mut self, name: &str, hir_fn: &HirFn, structs: &HashMap<String, HirStruct>, functions: &HashMap<String, HirFn>, externs: &[HirExternFn]) {
        self.var_ids.clear();
        self.next_var = 0;

        let safe_name = if name == "main" { "arca_main" } else { name };

        self.emit_indent();
        let ret_type = hir_fn.return_type.as_ref()
            .map(|t| self.hir_type_to_c(t, structs))
            .unwrap_or_else(|| "int64_t".to_string());
        self.emit(&ret_type);
        self.emit(" ");
        self.emit(safe_name);
        self.emit("(");
        for (i, param) in hir_fn.params.iter().enumerate() {
            if i > 0 { self.emit(", "); }
            let ctype = self.hir_type_to_c(&param.type_ann, structs);
            let vname = self.fresh_var(&param.name);
            self.emit(&format!("{} {}", ctype, vname));
        }
        self.emit(") {\n");
        self.indent += 1;

        // Emit all statements except possibly the last if it's an if-expression
        let stmt_count = hir_fn.body.statements.len();
        for (idx, stmt) in hir_fn.body.statements.iter().enumerate() {
            let is_last = idx == stmt_count - 1 && hir_fn.body.final_expr.is_none();
            if is_last {
                if let HirStmt::Expr(expr) = stmt {
                    let is_void_stmt = matches!(expr, HirExpr::Call { callee, .. }
                        if matches!(&**callee, HirExpr::VarRef(n) if n == "println" || n == "print"))
                        || matches!(expr, HirExpr::Loop(_));
                    if is_void_stmt {
                        self.emit_stmt(stmt, structs, functions, externs);
                        continue;
                    }
                    self.emit_indent();
                    self.emit("return ");
                    self.emit_expr(expr);
                    self.emit(";\n");
                    continue;
                }
            }
            self.emit_stmt(stmt, structs, functions, externs);
        }

        if let Some(ref fe) = hir_fn.body.final_expr {
            self.emit_indent();
            self.emit("return ");
            self.emit_expr(fe);
            self.emit(";\n");
        } else {
            let is_struct_ret = hir_fn.return_type.as_ref()
                .map(|t| matches!(t, TypeAnnotation::Named(n) if structs.contains_key(n)))
                .unwrap_or(false);
            if !is_struct_ret {
                self.emit_ln("return 0;");
            }
        }

        self.indent -= 1;
        self.emit_ln("}");
    }

    fn emit_stmt(&mut self, stmt: &HirStmt, structs: &HashMap<String, HirStruct>, functions: &HashMap<String, HirFn>, externs: &[HirExternFn]) {
        match stmt {
            HirStmt::VarDecl { name, init, .. } => {
                let vname = self.fresh_var(name);
                let var_type = init.as_ref()
                    .and_then(|e| self.infer_expr_type(e, structs, functions, externs))
                    .unwrap_or_else(|| "int64_t".to_string());
                self.emit_indent();
                self.emit(&format!("{} {} = ", var_type, vname));
                if let Some(init_expr) = init {
                    self.emit_expr(init_expr);
                } else {
                    self.emit("0");
                }
                self.emit(";\n");
            }
            HirStmt::Return(opt_expr) => {
                self.emit_indent();
                self.emit("return ");
                if let Some(expr) = opt_expr {
                    self.emit_expr(expr);
                } else {
                    self.emit("0");
                }
                self.emit(";\n");
            }
            HirStmt::Expr(expr) => {
                // If it's an if-expression as a statement, evaluate it
                if let HirExpr::If { cond, then_branch, else_branch } = expr {
                    self.emit_indent();
                    self.emit("if (");
                    self.emit_expr(cond);
                    self.emit(") {\n");
                    self.indent += 1;
                    for stmt in &then_branch.statements {
                        self.emit_stmt(stmt, structs, functions, externs);
                    }
                    if let Some(ref fe) = then_branch.final_expr {
                        self.emit_indent();
                        self.emit_expr(fe);
                        self.emit(";\n");
                    }
                    self.indent -= 1;
                    self.emit_indent();
                    if let Some(eb) = else_branch {
                        self.emit("} else {\n");
                        self.indent += 1;
                        match &**eb {
                            HirExpr::If { .. } => {
                                self.emit_indent();
                                self.emit_expr(eb);
                                self.emit("\n");
                            }
                            HirExpr::Block(b) => {
                                for stmt in &b.statements {
                                    self.emit_stmt(stmt, structs, functions, externs);
                                }
                                if let Some(ref fe) = b.final_expr {
                                    self.emit_indent();
                                    self.emit_expr(fe);
                                    self.emit(";\n");
                                }
                            }
                            _ => {
                                self.emit_indent();
                                self.emit_expr(eb);
                                self.emit(";\n");
                            }
                        }
                        self.indent -= 1;
                        self.emit_indent();
                    }
                    self.emit("}\n");
                } else {
                    let is_pure_literal = matches!(expr, HirExpr::Literal(LiteralKind::Int(_)));
                    if !is_pure_literal {
                        self.emit_indent();
                        self.emit_expr(expr);
                        self.emit(";\n");
                    }
                }
            }
            HirStmt::Defer(expr) => {
                self.emit_indent();
                self.emit_expr(expr);
                self.emit(";\n");
            }
            HirStmt::Destructure { fields, init, .. } => {
                let init_var = self.fresh_var("_destructure");
                self.emit_indent();
                self.emit(&format!("int64_t {} = ", init_var));
                self.emit_expr(init);
                self.emit(";\n");
                for fname in fields {
                    let vname = self.fresh_var(fname);
                    self.emit_ln(&format!("int64_t {} = {};", vname, init_var));
                }
            }
        }
    }

    fn emit_expr(&mut self, expr: &HirExpr) {
        match expr {
            HirExpr::Literal(lit) => match lit {
                LiteralKind::Int(n) => self.emit(&n.to_string()),
                LiteralKind::Float(f) => self.emit(&f.to_string()),
                LiteralKind::String(s) => {
                    let escaped = s
                        .replace('\\', "\\\\")
                        .replace('"', "\\\"")
                        .replace('\r', "\\r")
                        .replace('\t', "\\t")
                        .replace('\n', "\\n");
                    self.emit(&format!("\"{}\"", escaped));
                }
                LiteralKind::Bool(b) => self.emit(if *b { "1" } else { "0" }),
                LiteralKind::Char(c) => self.emit(&format!("'{}'", c)),
                LiteralKind::Null => self.emit("0"),
            },
            HirExpr::VarRef(name) => {
                if let Some(id) = self.var_ids.get(name) {
                    self.emit(&format!("{}_{}", name, id));
                } else {
                    // Built-in function calls
                    self.emit(name);
                }
            }
            HirExpr::Binary { left, op, right } => {
                self.emit("(");
                self.emit_expr(left);
                let op_str = match op {
                    BinaryOp::Add => " + ",
                    BinaryOp::Sub => " - ",
                    BinaryOp::Mul => " * ",
                    BinaryOp::Div => " / ",
                    BinaryOp::Rem => " % ",
                    BinaryOp::Equal => " == ",
                    BinaryOp::NotEqual => " != ",
                    BinaryOp::Less => " < ",
                    BinaryOp::LessEqual => " <= ",
                    BinaryOp::Greater => " > ",
                    BinaryOp::GreaterEqual => " >= ",
                    BinaryOp::And => " && ",
                    BinaryOp::Or => " || ",
                };
                self.emit(op_str);
                self.emit_expr(right);
                self.emit(")");
            }
            HirExpr::Unary { op, expr } => {
                let op_str = match op {
                    arca_ast::UnaryOp::Not => "!",
                    arca_ast::UnaryOp::Neg => "-",
                };
                self.emit(op_str);
                self.emit("(");
                self.emit_expr(expr);
                self.emit(")");
            }
            HirExpr::Call { callee, args } => {
                let callee_name = match &**callee {
                    HirExpr::VarRef(n) => n.clone(),
                    HirExpr::Member { object, property, .. } => {
                        let obj_str = format!("{:?}", object);
                        property.clone()
                    }
                    _ => "unknown".to_string(),
                };

                match callee_name.as_str() {
                    "println" => {
                        if args.len() == 1 {
                            // Check if it's a string or int literal
                            if let HirExpr::Literal(LiteralKind::String(_)) = &args[0] {
                                self.emit("arca_println_string(");
                                self.emit_expr(&args[0]);
                                self.emit(")");
                            } else {
                                self.emit("arca_println_int(");
                                self.emit_expr(&args[0]);
                                self.emit(")");
                            }
                        }
                    }
                    "print" => {
                        if args.len() == 1 {
                            if let HirExpr::Literal(LiteralKind::String(_)) = &args[0] {
                                self.emit("arca_print_string(");
                                self.emit_expr(&args[0]);
                                self.emit(")");
                            } else {
                                self.emit("arca_print_int(");
                                self.emit_expr(&args[0]);
                                self.emit(")");
                            }
                        }
                    }
                    _ => {
                        let fn_name = if callee_name == "main" { "arca_main" } else { &callee_name };
                        self.emit(fn_name);
                        self.emit("(");
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 { self.emit(", "); }
                            self.emit_expr(arg);
                        }
                        self.emit(")");
                    }
                }
            }
            HirExpr::Member { object, property, .. } => {
                self.emit_expr(object);
                self.emit(&format!(".{}", property));
            }
            HirExpr::StructInit { struct_name, fields } => {
                self.emit(&format!("({}){{", struct_name));
                for (i, (fname, fexpr)) in fields.iter().enumerate() {
                    if i > 0 { self.emit(", "); }
                    self.emit(&format!(".{}=", fname));
                    self.emit_expr(fexpr);
                }
                self.emit("}");
            }
            HirExpr::If { cond, then_branch, else_branch } => {
                self.emit("(");
                self.emit_expr(cond);
                self.emit(" ? ");
                // Extract value from then_branch
                if let Some(ref fe) = then_branch.final_expr {
                    self.emit_expr(fe);
                } else if let Some(first_stmt) = then_branch.statements.first() {
                    if let HirStmt::Expr(e) = first_stmt { self.emit_expr(e); }
                    else { self.emit("0"); }
                } else {
                    self.emit("0");
                }
                self.emit(" : ");
                // Extract value from else_branch — unwrap nested Block
                if let Some(eb) = else_branch {
                    match &**eb {
                        HirExpr::Block(b) => {
                            if let Some(ref fe) = b.final_expr { self.emit_expr(fe); }
                            else if let Some(HirStmt::Expr(e)) = b.statements.first() { self.emit_expr(e); }
                            else { self.emit("0"); }
                        }
                        other => self.emit_expr(other),
                    }
                } else {
                    self.emit("0");
                }
                self.emit(")");
            }
            HirExpr::Block(b) => {
                if let Some(ref fe) = b.final_expr {
                    self.emit_expr(fe);
                } else if let Some(HirStmt::Expr(e)) = b.statements.last() {
                    self.emit_expr(e);
                } else {
                    self.emit("0");
                }
            }
            HirExpr::Match { value, arms } => {
                // Simplistic match: check each arm's pattern against value
                self.emit("({ ");
                let val_var = self.fresh_var("_match_val");
                self.emit(&format!("int64_t {} = ", val_var));
                self.emit_expr(value);
                self.emit(";\n");
                let mut has_arms = false;
                for arm in arms {
                    match &arm.pattern {
                        arca_ast::Pattern::Wildcard => {
                            self.emit_indent();
                            self.emit("return ");
                            self.emit_expr(&arm.body);
                            self.emit(";\n");
                        }
                        arca_ast::Pattern::Identifier(name) => {
                            if name == "_" {
                                self.emit_indent();
                                self.emit("return ");
                                self.emit_expr(&arm.body);
                                self.emit(";\n");
                            } else {
                                let vname = self.fresh_var(name);
                                self.emit_ln(&format!("int64_t {} = {};", vname, val_var));
                                self.emit_indent();
                                self.emit("return ");
                                self.emit_expr(&arm.body);
                                self.emit(";\n");
                            }
                        }
                        _ => {}
                    }
                    has_arms = true;
                }
                if !has_arms {
                    self.emit_ln("return 0;");
                }
                self.emit("0; })");
            }
            HirExpr::Loop(body) => {
                self.emit("while (1) {\n");
                self.indent += 1;
                for stmt in &body.statements {
                    self.emit_stmt(stmt, &HashMap::new(), &HashMap::new(), &[]);
                }
                if let Some(ref fe) = body.final_expr {
                    self.emit_indent();
                    self.emit_expr(fe);
                    self.emit(";\n");
                }
                self.indent -= 1;
                self.emit_indent();
                self.emit("}");
            }
            HirExpr::Comptime(b) | HirExpr::TryBlock(b) | HirExpr::GroupBlock(b) | HirExpr::Spawn(b) => {
                if let Some(ref fe) = b.final_expr {
                    self.emit_expr(fe);
                } else {
                    self.emit("0");
                }
            }
            HirExpr::Closure { body, .. } => self.emit_expr(body),
            HirExpr::Borrow(inner) => { self.emit("(&"); self.emit_expr(inner); self.emit(")"); }
            HirExpr::Move(inner) => self.emit_expr(inner),
        }
    }

    fn hir_type_to_c(&self, ann: &TypeAnnotation, structs: &HashMap<String, HirStruct>) -> String {
        match ann {
            TypeAnnotation::Named(name) => match name.as_str() {
                "i8" => "int8_t".to_string(),
                "i16" => "int16_t".to_string(),
                "i32" => "int32_t".to_string(),
                "i64" | "int" => "int64_t".to_string(),
                "u8" => "uint8_t".to_string(),
                "u16" => "uint16_t".to_string(),
                "u32" => "uint32_t".to_string(),
                "u64" => "uint64_t".to_string(),
                "f32" => "float".to_string(),
                "f64" => "double".to_string(),
                "bool" => "bool".to_string(),
                "string" => "const char*".to_string(),
                "void" => "void".to_string(),
                "c_void_ptr" => "void*".to_string(),
                _ => {
                    if structs.contains_key(name) {
                        name.clone()
                    } else {
                        "int64_t".to_string()
                    }
                }
            },
            TypeAnnotation::Reference { inner, .. } => {
                let inner_c = self.hir_type_to_c(inner, structs);
                format!("{}*", inner_c)
            }
            _ => "int64_t".to_string(),
        }
    }

    fn infer_expr_type(&self, expr: &HirExpr, structs: &HashMap<String, HirStruct>, functions: &HashMap<String, HirFn>, externs: &[HirExternFn]) -> Option<String> {
        match expr {
            HirExpr::Call { callee, .. } => {
                if let HirExpr::VarRef(name) = &**callee {
                    if let Some(f) = functions.get(name) {
                        if let Some(ref ret) = f.return_type {
                            return Some(self.hir_type_to_c(ret, structs));
                        }
                    }
                    if let Some(ext) = externs.iter().find(|e| e.name == *name) {
                        if let Some(ref ret) = ext.return_type {
                            return Some(self.hir_type_to_c(ret, structs));
                        }
                    }
                }
                None
            }
            HirExpr::Literal(lit) => match lit {
                LiteralKind::Int(_) => Some("int64_t".to_string()),
                LiteralKind::Float(_) => Some("double".to_string()),
                LiteralKind::String(_) => Some("const char*".to_string()),
                LiteralKind::Bool(_) => Some("bool".to_string()),
                LiteralKind::Char(_) => Some("char".to_string()),
                LiteralKind::Null => Some("int64_t".to_string()),
            },
            HirExpr::StructInit { struct_name, .. } => {
                if structs.contains_key(struct_name) {
                    Some(struct_name.clone())
                } else {
                    Some("int64_t".to_string())
                }
            }
            _ => None,
        }
    }

    pub fn generate_c(&self, _module: &AirModule) -> String {
        let mut out = String::new();
        out.push_str("// Generated by Arca Compiler Portable C Backend\n");
        out.push_str("#include <stdio.h>\n");
        out.push_str("#include <stdint.h>\n");
        out.push_str("#include <stdbool.h>\n\n");
        out.push_str("int main(int argc, char** argv) {\n");
        out.push_str("    printf(\"Hello from Arca Portable C Code Generator!\\n\");\n");
        out.push_str("    return 0;\n");
        out.push_str("}\n");
        out
    }

    pub fn generate_llvm(&self, _module: &AirModule) -> String {
        let mut out = String::new();
        out.push_str("; ModuleID = 'arca_module'\n");
        out.push_str("source_filename = \"arca_module\"\n");
        out.push_str("target triple = \"aarch64-apple-darwin\"\n\n");
        out.push_str("define i32 @main() {\n");
        out.push_str("entry:\n");
        out.push_str("  ret i32 0\n");
        out.push_str("}\n");
        out
    }

    pub fn generate_native_object(&self, _module: &AirModule) -> Vec<u8> {
        vec![0xCF, 0xFA, 0xED, 0xFE, 0x0C, 0x00, 0x00, 0x01]
    }
}
