//! Arca.lock lockfile structure, generator, and parser.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LockPackage {
    pub name: String,
    pub version: String,
    pub checksum: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Lockfile {
    pub version: u32,
    pub packages: HashMap<String, LockPackage>,
}

impl Lockfile {
    pub fn new() -> Self {
        Self {
            version: 1,
            packages: HashMap::new(),
        }
    }

    pub fn parse<S: AsRef<str>>(content: S) -> Result<Self, String> {
        let mut packages = HashMap::new();
        let mut cur_name = String::new();
        let mut cur_ver = String::new();
        let mut cur_sum = String::new();

        for line in content.as_ref().lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }

            if trimmed == "[[package]]" {
                if !cur_name.is_empty() {
                    packages.insert(
                        cur_name.clone(),
                        LockPackage {
                            name: cur_name.clone(),
                            version: cur_ver.clone(),
                            checksum: cur_sum.clone(),
                        },
                    );
                }
                cur_name.clear();
                cur_ver.clear();
                cur_sum.clear();
                continue;
            }

            if let Some((k, v)) = trimmed.split_once('=') {
                let key = k.trim();
                let val = v.trim().trim_matches('"').trim_matches('\'');

                match key {
                    "name" => cur_name = val.to_string(),
                    "version" => cur_ver = val.to_string(),
                    "checksum" => cur_sum = val.to_string(),
                    _ => {}
                }
            }
        }

        if !cur_name.is_empty() {
            packages.insert(
                cur_name.clone(),
                LockPackage {
                    name: cur_name,
                    version: cur_ver,
                    checksum: cur_sum,
                },
            );
        }

        Ok(Self {
            version: 1,
            packages,
        })
    }

    pub fn load_from_dir<P: AsRef<Path>>(dir: P) -> Result<Self, String> {
        let lock_path = dir.as_ref().join("Arca.lock");
        if !lock_path.exists() {
            return Ok(Self::new());
        }

        let content = fs::read_to_string(&lock_path)
            .map_err(|e| format!("Failed to read 'Arca.lock': {}", e))?;
        Self::parse(content)
    }

    pub fn save_to_dir<P: AsRef<Path>>(&self, dir: P) -> Result<(), String> {
        let lock_path = dir.as_ref().join("Arca.lock");
        let mut out = String::from("# Generated by Arca Package Manager. DO NOT EDIT.\nversion = 1\n\n");

        for pkg in self.packages.values() {
            out.push_str("[[package]]\n");
            out.push_str(&format!("name = \"{}\"\n", pkg.name));
            out.push_str(&format!("version = \"{}\"\n", pkg.version));
            out.push_str(&format!("checksum = \"{}\"\n\n", pkg.checksum));
        }

        fs::write(lock_path, out).map_err(|e| format!("Failed to write 'Arca.lock': {}", e))
    }
}
