use arca_air::AirModule;
use arca_backend::{BackendKind, CodeGenerator, TargetArch};

#[test]
fn test_c_backend_generation() {
    let module = AirModule::new("test_mod".into());
    let mut gen = CodeGenerator::new(BackendKind::C, TargetArch::C);

    let c_code = gen.generate_c_from_air(&module);
    assert!(c_code.contains("#include \"arca_runtime.h\""));
    assert!(c_code.contains("// Generated by Arca C Backend (AIR)"));
}
